### ISSUE TITLE
Add .editorconfig file to prevent code formatting issues

### ISSUE THREAD

**Issue by jkernech** [dial-once/sample-node-microservice#1]

**Comment by mrister** [comment]
@jkernech .editorconfig is good but limited and won't help us with code style (e.g. position of braces on if, function etc) Unfortunately also jshint won't help here either. I think we would need to move to eslint and use arbinb style (plugin) to do that. cc @PuKoren .

**Comment by mrister** [comment]
stuff supported by .editorconfig. https://github.com/sindresorhus/atom-editorconfig

**Comment by PuKoren** [comment]
+1 for eslint

**Comment by jkernech** [comment]
@mrister Should be another issue since the purpose of both is different. One is to configure your editor and prevent bad formatting while writing code, the other to validate the code style.

**Comment by mrister** [comment]
@jkernech yup, I agree fully!
